openapi: 3.0.0
info:
  title: BETA - API de Autopay - Solicitud de Balance
  version: 1.0.0
paths:
  /autopay/balance:
    post:
      summary: Obtener balance
      operationId: post-balance
      parameters:
        - schema:
            type: string
            example: application/json;charset=UTF-8
          in: header
          name: Content-Type
      responses:
        "200":
          description: Respuesta satisfactoria con el balance.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/Status'
                  id:
                    type: string
                    format: uuid
                    example: "2972c13d-6315-4da3-80d7-64c24eb232ad"
                  amount:
                    $ref: "#/components/schemas/Amount"
                  min_amount:
                    $ref: "#/components/schemas/Amount"
        "4XX":
          description: Error en la solicitud.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/Status'
      description: 'Este endpoint devuelve un balance con su información de montos'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                auth:
                  $ref: '#/components/schemas/Auth'
                reference:
                  type: string
                  description: Referencia del auto pago
                  example: "ACC00012345"
                  maxLength: 32
                id:
                  type: string
                  format: uuid
                  description: Identificador único del auto pago
                  maxLength: 36
                  example: "2972c13d-6315-4da3-80d7-64c24eb232ad"
        description: ''
    parameters: [ ]
  /autopay/settlement:
    post:
      summary: Notificar pago
      operationId: post-settlement
      parameters:
        - schema:
            type: string
            example: application/json;charset=UTF-8
          in: header
          name: Content-Type
      responses:
        "200":
          description: Notificación registrada correctamente.
          content:
            application/json:
              schema:
                type: object
                required: [ status, id ]
                properties:
                  status:
                    $ref: '#/components/schemas/Status'
                  id:
                    type: string
                    format: uuid
                    example: "2972c13d-6315-4da3-80d7-64c24eb232ad"
        "4XX":
          description: Error en la solicitud.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
      description: 'Este endpoint registra y retorna únicamente el estado de la notificación (settlement).'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required: [ reference, id, transaction ]
              properties:
                auth:
                  $ref: '#/components/schemas/Auth'
                reference:
                  type: string
                  example: "ACC-00012345"
                id:
                  type: string
                  format: uuid
                  example: "2972c13d-6315-4da3-80d7-64c24eb232ad"
                transaction:
                  $ref: "#/components/schemas/Transaction"
  /autopay/webhook:
    post:
      summary: Recepción de notificaciones Autopay
      description: |
        Este endpoint recibe notificaciones (webhooks) cuando ocurren eventos
        relacionados con los pagos automáticos (`autopay`).
        
        ### Seguridad de la firma:
        La cabecera `signature` se genera como:
        ```
        Base64(SHA-256(secretKey + data + date))
        ```
        donde:
        - `secretKey`: Clave compartida entre el cliente y el servidor.
        - `data`: Contenido del objeto `data` serializado en JSON.
        - `date`: Fecha del evento.

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WebhookEvent'
      responses:
        "200":
          description: Webhook recibido correctamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: '#/components/schemas/Status'
        "4XX":
          description: Error en la validación del payload o firma incorrecta.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    $ref: "#/components/schemas/Status"
components:
  schemas:
    Auth:
      title: Autenticación
      type: object
      description: Autenticación
      properties:
        login:
          type: string
          description: |
            Identificador del sitio
        tranKey:
          type: string
          description: |
            Credencial **tranKey** generado
        nonce:
          type: string
          description: |
            Valor **aleatorio** para cada solicitud codificado en **Base64**.
        seed:
          type: string
          description: |
            Fecha **actual**, la cual se genera en formato **ISO 8601**.
    WebhookEvent:
      type: object
      required:
        - type
        - site
        - signature
        - date
        - data
      properties:
        type:
          type: string
          enum:
            - AUTOPAY_UPDATED
            - AUTOPAY_FAILED
            - AUTOPAY_DELETED
          description: Tipo de evento notificado.
        site:
          type: string
          format: uuid
          description: Identificador único del sitio o comercio asociado.
          example: "2972c13d-6315-4da3-80d7-64c24eb232ad"
        signature:
          type: string
          description: Firma digital del mensaje en formato Base64.
          example: "Base64(SHA-256(secretKey + data + date))"
        date:
          type: string
          format: date-time
          description: Fecha y hora del evento.
          example: "2023-01-19 15:57:23"
        data:
          type: object
          required:
            - id
          properties:
            id:
              type: string
              format: uuid
              description: Identificador interno del autopay.
              example: "2972c13d-6315-4da3-80d7-64c24eb232ad"
    Status:
      title: Status
      type: object
      description: Estructura para definir estados de respuestas
      x-internal: false
      properties:
        reason:
          type: string
          enum:
            - 100
            - 101
            - 102
            - 103
            - 104
            - 00
            - BR
            - X3
            - XH
            - ?-
            - 05
            - NF
          description: Código de los estados. (consulte la columna código en Documentos/Códigos de razón)
          example: '00'

        status:
          type: string
          enum:
            - OK
            - FAILED
          description: Nombre de los estados. (consulte la columna Significado en Documentos/Códigos de razón)
          example: "OK"
        message:
          type: string
          description: Mensaje para aclarar el estado
          example: "Respuesta satisfactoria"
        date:
          type: string
          format: date-time
          description: Mensaje para aclarar el estado
          example: "2025-09-29T17:09:29-05:00"
    Amount:
      title: "Amount"
      type: "object"
      description: "Estructura que contiene la información acerca del pago de la transacción requerida al servicio web"
      required:
        - "currency"
        - "total"
      properties:
        currency:
          type: "string"
          enum:
            - "USD"
            - "COP"
            - "CRC"
            - "EUR"
            - "CAD"
            - "AUD"
            - "GBP"
            - "MXN"
            - "CLP"
          example: "COP"
          minLength: 3
          maxLength: 3
        total:
          type: "number"
        taxes:
          type: "array"
          items:
            $ref: "#/components/schemas/TaxDetail"
        details:
          type: "array"
          items:
            $ref: "#/components/schemas/AmountDetail"
    TaxDetail:
      title: "TaxDetail"
      type: "object"
      description: "Estructura para almacenar información sobre un impuesto."
      properties:
        kind:
          type: "string"
          example: "valueAddedTax"
          description: "Tipo de impuesto reportado"
          enum:
            - valueAddedTax
            - exciseDuty
            - ice
            - airportTax
            - stateTax
            - reducedStateTax
            - municipalTax
        amount:
          type: "number"
        base:
          type: "number"
    AmountDetail:
      title: "AmountDetail"
      type: "object"
      description: "Estructura para almacenar información sobre un valor adicional."
      properties:
        kind:
          type: "string"
        amount:
          type: "number"
    AmountConversion:
      title: "AmountConversion"
      type: "object"
      description: "Estructura para definir el factor de conversión y los valores."
      properties:
        from:
          $ref: "#/components/schemas/AmountBase"
        to:
          $ref: "#/components/schemas/AmountBase"
        factor:
          type: "number"
    AmountBase:
      title: "AmountBase"
      type: "object"
      description: "Estructura que representa una cantidad que define la moneda y el total."
      properties:
        currency:
          type: "string"
        total:
          type: "number"
    Transaction:
      description: "Contiene información sobre una transacción"
      type: "object"
      title: ""
      properties:
        status:
          $ref: "#/components/schemas/Status"
        date:
          type: "string"
          description: |
            EJ: `2021-09-20T21:51:59-05:00`
        transactionDate:
          type: "string"
          description: |
            EJ: `2021-09-20T21:51:59-05:00`
        internalReference:
          type: "number"
        reference:
          type: "string"
          minLength: 1
        paymentMethod:
          type: "string"
          minLength: 1
        franchise:
          type: "string"
          minLength: 1
        franchiseName:
          type: "string"
          minLength: 1
        issuerName:
          type: "string"
          minLength: 1
          nullable: true
        amount:
          $ref: "#/components/schemas/Amount"
        conversion:
          $ref: "#/components/schemas/AmountConversion"
        authorization:
          type: "string"
          minLength: 1
          nullable: true
        receipt:
          type: "string"
          maxLength: 16
          nullable: true
        type:
          type: "string"
          minLength: 1
        refunded:
          type: "boolean"
        lastDigits:
          type: "string"
          minLength: 1
          nullable: true
        provider:
          type: "string"
          enum:
            - "CREDIBANCO"
            - "REDEBAN"
            - "INTERDIN"
            - "DATAFAST"
            - "TUYA-DIRECT"
            - "BRASPAG"
            - "TRANSERVER"
            - "SABRE"
            - "EVERTEC"
            - "ACH"
            - "ATH-AVALNET"
            - "SUPERGIROS"
            - "TECNICARD"
            - "MEDIANET"
            - "AUSTRO"
            - "COMFANDI"
            - "PAYSTUDIO"
            - "FLAMINGO"
            - "ATH-MOVIL"
            - "EBUS"
            - "BANCOLOMBIA"
        discount:
          type: "string"
        processorFields:
          type: "object"
          properties:
            id:
              type: "string"
            b24:
              type: "string"
        additional:
          type: "object"
          description: |
            Ver más en [Datos adicionales](/gateway/additional-data)
        preAuthorization:
          type: "object"
          items:
            type: "object"
            properties:
              condition:
                type: "string"
              internalReference:
                type: "number"
              authorization:
                type: "string"
                minLength: 1
                nullable: true
              receipt:
                type: "string"
                minLength: 1
                nullable: true
              amount:
                $ref: "#/components/schemas/Amount"
              salt:
                type: "string"
        dispersion:
          type: "array"
          items:
            type: "object"
            properties:
              status:
                $ref: "#/components/schemas/Status"
              agreement:
                type: "integer"
                nullable: true
              agreementType:
                type: "string"
                enum:
                  - "AIRLINE"
                  - "MERCHANT"
              authorization:
                type: "string"
                minLength: 1
                nullable: true
              receipt:
                type: "string"
                minLength: 1
                nullable: true
              amount:
                $ref: "#/components/schemas/Amount"
              refunded:
                type: "boolean"
              paymentMethod:
                type: "string"
      required:
        - "status"
        - "provider"
        - "internalReference"
        - "reference"
        - "paymentMethod"
        - "franchise"
        - "franchiseName"
        - "issuerName"
        - "amount"
        - "conversion"
        - "authorization"
        - "receipt"
        - "type"
        - "refunded"
        - "lastDigits"
        - "discount"
        - "processorFields"
        - "additional"
