openapi: 3.0.0
info:
  title: BETA - API de Autopay - Solicitud de Balance
  version: 1.0.0
  description: |
    Endpoint para consultar el balance de una cuenta en el sistema Autopay.

paths:
  /autopay/balance:
    post:
      summary: Obtener balance
      operationId: post-balance
      parameters:
        - schema:
            type: string
            example: application/json;charset=UTF-8
          in: header
          name: Content-Type
      responses:
        "200":
          description: Respuesta satisfactoria con el balance.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: object
                    properties:
                      status:
                        type: string
                        example: "OK"
                      reason:
                        type: string
                        example: "00"
                      message:
                        type: string
                        example: "Respuesta satisfactoria"
                      date:
                        type: string
                        format: date-time
                        example: "2025-09-29T17:09:29-05:00"
                  id:
                    type: string
                    format: uuid
                    example: "2972c13d-6315-4da3-80d7-64c24eb232ad"
                  amount:
                    type: object
                    properties:
                      currency:
                        type: string
                        example: "USD"
                      total:
                        type: number
                        example: 10
                  min_amount:
                    type: object
                    properties:
                      currency:
                        type: string
                        example: "USD"
                      total:
                        type: number
                        example: 5
        "400":
          description: Error en la solicitud.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
              example:
                status:
                  status: "FAILED"
                  reason: "XH"
                  message: "Respuesta insatisfactoria"
                  date: "2025-09-29T17:09:29-05:00"
        "401":
          description: No autorizado.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
              example:
                status:
                  status: "FAILED"
                  reason: "UNAUTHORIZED"
                  message: "Token inválido o expirado"
                  date: "2025-09-29T17:09:29-05:00"
        "404":
          description: Recurso no encontrado o referencia inexistente.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
              example:
                status:
                  status: "FAILED"
                  reason: "XH"
                  message: "Respuesta insatisfactoria"
                  date: "2025-09-29T17:09:29-05:00"
      description: 'Este endpoint devolvera un balance con su informacion de montos'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                auth:
                  type: object
                  description: Autenticación
                  properties:
                    login:
                      type: string
                      description: |
                        Identificador del sitio
                    tranKey:
                      type: string
                      description: |
                        Credencial **tranKey** generado
                    nonce:
                      type: string
                      description: |
                        Valor **aleatorio** para cada solicitud codificado en **Base64**.
                    seed:
                      type: string
                      description: |
                        Fecha **actual**, la cual se genera en formato **ISO 8601**.
                reference:
                  type: string
                  description: Referencia de la cuenta o transacción.
                  example: "ACC-00012345"
                id:
                  type: string
                  format: uuid
                  description: Identificador único de la solicitud.
                  example: "2972c13d-6315-4da3-80d7-64c24eb232ad"
            examples:
              example-success:
                value:
                  id: a2ce48f8-bba3-11ea-b3de-0242ac13352b
                  transaction:
                    reference: f0ce88f8-bba3-11ea-b3de-0242ac130004
                    status:
                      name: approved
        description: ''
    parameters: [ ]
components:
  schemas:
    Status:
      title: Status
      type: object
      description: Estructura para definir estados de respuestas
      x-internal: false
      properties:
        code:
          type: integer
          format: int32
          enum:
            - 100
            - 101
            - 102
            - 103
            - 104
          description: Código de los estados. (consulte la columna código en Documentos/Elementos de datos Tabla 1)
        name:
          type: string
          enum:
            - OK
            - FAILED
          description: Nombre de los estados. (consulte la columna Significado en Documentos/Elementos de datos Tabla 1)
        message:
          type: string
          description: Mensaje para aclarar el estado
      required:
        - code
        - name
