openapi: 3.1.0
info:
  title: Placetopay Base API
  version: 1.0.0

components:
  schemas:
    Status:
      title: "Status"
      type: "object"
      description: "Structure that contains information about a request or payment, informing its current status."
      properties:
        status:
          type: "string"
          enum:
            - "OK"
            - "FAILED"
            - "APPROVED"
            - "APPROVED_PARTIAL"
            - "PARTIAL_EXPIRED"
            - "REJECTED"
            - "PENDING"
            - "PENDING_VALIDATION"
            - "PENDING_PROCESS"
            - "REFUNDED"
            - "REVERSED"
            - "ERROR"
            - "UNKNOWN"
            - "MANUAL"
            - "DISPUTE"
        reason:
          type: "string"
          minLength: "1"
          maxLength: "4"
        message:
          type: "string"
        date:
          type: "string"
          example: "2021-09-21T09:34:48-05:00"
    Authentication:
      title: "Autenticación"
      type: "object"
      properties:
        login:
          type: "string"
          description: Site identifier
        tranKey:
          type: "string"
          description: Generated **tranKey** credential
        nonce:
          type: "string"
          description: |
            **Random** value for each request encoded in **Base64**.
        seed:
          type: "string"
          description: |
            **Timestamp**, in **ISO 8601** format.
      description: "Structure that contains the site authentication information generated according to the WSSE UsernameToken Profile 1.1"
    Amount:
      title: "Amount"
      type: "object"
      description: "Structure that contains the information about the payment of the transaction required to the web service"
      properties:
        currency:
          type: "string"
          description: |
            Alphabetical code of the currency to be used (ISO 4217 alpha code)
          enum:
            - "USD"
            - "COP"
            - "CRC"
            - "EUR"
            - "CAD"
            - "AUD"
            - "GBP"
            - "MXN"
            - "CLP"
          example: "COP"
          minLength: 3
          maxLength: 3
        total:
          description: |
            Total value in the indicated base currency
          example: 2000
          type: "number"
        taxes:
          type: "array"
          description: |
            Structure to define taxes in the payment process.
          items:
            $ref: "#/components/schemas/TaxDetail"
        details:
          description: |
            Structure to define additional details of the amount in the payment process.
          type: "array"
          items:
            $ref: "#/components/schemas/AmountDetail"
      required:
        - "currency"
        - "total"
    TaxDetail:
      title: "TaxDetail"
      type: "object"
      description: "Structure to store information about a tax."
      properties:
        kind:
          type: "string"
          example: "valueAddedTax"
          description: |
            Tax type identifier
          enum:
            - valueAddedTax
            - exciseDuty
            - ice
            - airportTax
            - stateTax
            - reducedStateTax
            - municipalTax
        amount:
          type: "number"
          description: |
            Full amount of tax
        base:
          description: |
            Base amount on which the tax is calculated
          type: "number"
    AmountDetail:
      title: "AmountDetail"
      type: "object"
      description: "Structure to store information about an additional value."
      properties:
        kind:
          type: "string"
          description: |
            Detail Type Identifier.
        amount:
          type: "number"
          description: |
            Total amount of detail
    AmountConversion:
      title: "AmountConversion"
      type: "object"
      description: "Structure to define the conversion factor and values."
      properties:
        from:
          $ref: "#/components/schemas/AmountBase"
        to:
          $ref: "#/components/schemas/AmountBase"
        factor:
          type: "number"
          example: 1
          description: Conversion factor
    AmountBase:
      title: "AmountBase"
      type: "object"
      description: "Structure that represents an amount that defines the currency and the total."
      properties:
        currency:
          type: "string"
          description: |
            Currency according to ISO 4217 (alphabetic code).
        total:
          description: |
            Total value.
          type: "number"
    Transaction:
      description: "Transaction data"
      type: "object"
      x-examples:
        Ejemplo:
          status:
            status: "APPROVED"
            reason: "00"
            message: "approved"
            date: "2021-09-20T20:10:57-05:00"
          date: "2021-09-20T20:10:56-05:00"
          transactionDate: "2021-09-20T20:10:56-05:00"
          internalReference: 2
          reference: "1234567890"
          paymentMethod: "DF_VS"
          franchise: "visa"
          franchiseName: "Visa"
          issuerName: "Testing Bank"
          amount:
            currency: "USD"
            total: 1
          conversion:
            from:
              currency: "USD"
              total: 1
            to:
              currency: "USD"
              total: 1
            factor: 1
          authorization: "000000"
          receipt: "2"
          type: "AUTH_ONLY"
          refunded: "false"
          lastDigits: "0008"
          provider: "DATAFAST"
          discount:
          processorFields:
            id: "de7c331a0f5bebdd1996250296cdaf37"
            b24: "000"
          additional:
            merchantCode: "1000000505"
            terminalNumber: "PY100404"
            credit:
              code: "0"
              type: "00"
              groupCode: "C"
              installments: 0
            totalAmount: 1
            iceAmount: 0
            batch:
            line:
            bin: "411076"
            expiration: "1221"
      title: ""
      properties:
        status:
          $ref: "#/components/schemas/Status"
        date:
          type: "string"
          format: date-time
          description: "Date when the transaction was created (ISO 8601, timezone offset required). Example: `2021-09-20T21:51:59-05:00`."
        transactionDate:
          type: "string"
          format: date-time
          description: "Processing date at provider (may differ from date)."
        internalReference:
          type: "number"
          description: "Platform internal reference."
          minimum: 1
        reference:
          type: "string"
          description: "Merchant order reference."
          minLength: 1
        paymentMethod:
          type: "string"
          description: "Payment method code."
          minLength: 2
        franchise:
          type: "string"
          description: "Franchise code."
          enum:
            - "visa"
            - "visa_electron"
            - "amex"
            - "master"
            - "codensa"
            - "diners"
            - "jbc"
            - "discover"
            - "ris"
            - "credencial"
            - "comfama"
            - "colsubsidio"
            - "falabella"
            - "elo"
            - "somos"
            - "tuya"
            - "exito"
            - "alkosto"
            - "maestro"
            - "mefia"
            - "ath_card"
            - "ath"
            - "athmv"
            - "bancolombia"
            - "cooperativa"
            - "debito"
            - "pagoefectivo"
            - "cafam"
            - "efecty"
            - "gana"
            - "masterpass"
            - "ppd"
            - "pse"
            - "safetypay"
            - "supergiros"
            - "visa_checkout"
            - "procesa"
            - "comfandi"
            - "ach"
            - "telered"
            - "aval"
            - "dilo"
            - "banco_bogota"
            - "ebt"
            - "alia"
        franchiseName:
          type: "string"
          description: "Franchise display name."
          minLength: 1
        issuerName:
          type: "string"
          description: "Issuing bank name."
          minLength: 1
          nullable: true
        amount:
          $ref: "#/components/schemas/Amount"
        conversion:
          $ref: "#/components/schemas/AmountConversion"
        authorization:
          type: "string"
          description: "Authorization code."
          minLength: 1
          maxLength: 32
          nullable: true
        receipt:
          type: "string"
          description: "Receipt / ticket number."
          maxLength: 16
          minLength: 1
          nullable: true
        type:
          type: "string"
          description: "Transaction operation type."
          minLength: 1
          enum:
            - 'AUTH_ONLY'
            - 'AUTH_CAPTURE'
            - 'CAPTURE_ONLY'
            - 'CREDIT'
            - 'SETTLE'
            - 'VOID'
            - 'CHARGEBACK'
            - 'DISPUTE'
            - 'DISPUTE_LOSS'
            - 'DISPUTE_WIN'
            - 'DISPERSION'
            - 'REFUND'
            - 'PRE_AUTH'
            - 'CHECKIN'
            - 'CHECKOUT'
            - 'RE_AUTH'
            - 'DISPERSION_CAPTURE'
            - 'DISPERSION_SETTLE'
            - 'DISPERSION_CREDIT'
        refunded:
          type: "boolean"
          description: "Refunded flag."
        lastDigits:
          type: "string"
          description: "Masked card, last digits."
          minLength: 2
          nullable: true
        provider:
          type: "string"
          description: "Processor/provider code."
          enum:
            - "CREDIBANCO"
            - "REDEBAN"
            - "INTERDIN"
            - "DATAFAST"
            - "TUYA-DIRECT"
            - "BRASPAG"
            - "TRANSERVER"
            - "SABRE"
            - "EVERTEC"
            - "ACH"
            - "ATH-AVALNET"
            - "SUPERGIROS"
            - "TECNICARD"
            - "MEDIANET"
            - "AUSTRO"
            - "COMFANDI"
            - "PAYSTUDIO"
            - "FLAMINGO"
            - "ATH-MOVIL"
            - "EBUS"
            - "BANCOLOMBIA"
        discount:
          type: "object"
          nullable: true
          description: "Applied discount info."
          properties:
            code:
              type: string
              description: "Discount code."
              maxLength: 32
            type:
              type: string
              description: "Discount type."
              maxLength: 32
            amount:
              type: number
              description: "Discount amount."
              minimum: 0
            base:
              type: number
              description: "Base used."
              minimum: 0
            percentage:
              type: number
              description: "Discount percent."
              minimum: 0
              maximum: 100
        processorFields:
          type: "object"
          description: "Raw processor fields."
          properties:
            id:
              type: "string"
              description: "Processor id."
              maxLength: 64
            b24:
              type: "string"
              description: "Extra field."
        additional:
          type: "object"
          description: |
            See more in [Additional data](/en/gateway/additional-data)
        preAuthorization:
          type: "object"
          description: "Pre-authorization segments."
          items:
            type: "object"
            properties:
              condition:
                type: "string"
                description: "Segment condition."
              internalReference:
                type: "number"
                description: "Segment reference."
              authorization:
                type: "string"
                description: "Segment auth code."
                minLength: 1
                nullable: true
              receipt:
                type: "string"
                description: "Segment receipt."
                minLength: 1
                nullable: true
              amount:
                $ref: "#/components/schemas/Amount"
              salt:
                type: "string"
                description: "Segment salt."
        dispersion:
          type: "array"
          description: "Dispersion splits list."
          items:
            type: "object"
            properties:
              status:
                $ref: "#/components/schemas/Status"
              agreement:
                type: "integer"
                description: "Agreement id."
                nullable: true
              agreementType:
                type: "string"
                description: "Agreement type."
                enum:
                  - "AIRLINE"
                  - "MERCHANT"
              authorization:
                type: "string"
                description: "Leg auth code."
                minLength: 1
                nullable: true
              receipt:
                type: "string"
                description: "Leg receipt."
                minLength: 1
                nullable: true
              amount:
                $ref: "#/components/schemas/Amount"
              refunded:
                type: "boolean"
                description: "Leg refunded flag."
              paymentMethod:
                type: "string"
                description: "Leg payment method."
      required:
        - "status"
        - "provider"
        - "internalReference"
        - "reference"
        - "paymentMethod"
        - "franchise"
        - "franchiseName"
        - "amount"
        - "authorization"
        - "receipt"
        - "type"
        - "refunded"
        - "processorFields"
