openapi: 3.1.0
info:
  title: Placetopay Base API
  version: 1.0.0

components:
  schemas:
    Status:
      title: "Status"
      type: "object"
      description: "Structure that contains information about a request or payment, informing its current status."
      properties:
        status:
          type: "string"
          enum:
            - "OK"
            - "FAILED"
            - "APPROVED"
            - "APPROVED_PARTIAL"
            - "PARTIAL_EXPIRED"
            - "REJECTED"
            - "PENDING"
            - "PENDING_VALIDATION"
            - "PENDING_PROCESS"
            - "REFUNDED"
            - "REVERSED"
            - "ERROR"
            - "UNKNOWN"
            - "MANUAL"
            - "DISPUTE"
        reason:
          type: "string"
          minLength: "1"
          maxLength: "4"
        message:
          type: "string"
        date:
          type: "string"
          example: "2021-09-21T09:34:48-05:00"
    Authentication:
      title: "Autenticación"
      type: "object"
      properties:
        login:
          type: "string"
          description: Site identifier
        tranKey:
          type: "string"
          description: Generated **tranKey** credential
        nonce:
          type: "string"
          description: |
            **Random** value for each request encoded in **Base64**.
        seed:
          type: "string"
          description: |
            **Timestamp**, in **ISO 8601** format.
      description: "Structure that contains the site authentication information generated according to the WSSE UsernameToken Profile 1.1"
    Amount:
      title: "Amount"
      type: "object"
      description: "Structure that contains the information about the payment of the transaction required to the web service"
      properties:
        currency:
          type: "string"
          enum:
            - "USD"
            - "COP"
            - "CRC"
            - "EUR"
            - "CAD"
            - "AUD"
            - "GBP"
            - "MXN"
            - "CLP"
          example: "COP"
          minLength: 3
          maxLength: 3
        total:
          type: "number"
        taxes:
          type: "array"
          items:
            $ref: "#/components/schemas/TaxDetail"
        details:
          type: "array"
          items:
            $ref: "#/components/schemas/AmountDetail"
      required:
        - "currency"
        - "total"
    TaxDetail:
      title: "TaxDetail"
      type: "object"
      description: "Structure to store information about a tax."
      properties:
        kind:
          type: "string"
          example: "valueAddedTax"
          description: "Tipo de impuesto reportado"
          enum:
            - valueAddedTax
            - exciseDuty
            - ice
            - airportTax
            - stateTax
            - reducedStateTax
            - municipalTax
        amount:
          type: "number"
        base:
          type: "number"
    AmountDetail:
      title: "AmountDetail"
      type: "object"
      description: "Structure to store information about an additional value."
      properties:
        kind:
          type: "string"
        amount:
          type: "number"
    AmountConversion:
      title: "AmountConversion"
      type: "object"
      description: "Structure to define the conversion factor and values."
      properties:
        from:
          $ref: "#/components/schemas/AmountBase"
        to:
          $ref: "#/components/schemas/AmountBase"
        factor:
          type: "number"
    AmountBase:
      title: "AmountBase"
      type: "object"
      description: "Structure that represents an amount that defines the currency and the total."
      properties:
        currency:
          type: "string"
        total:
          type: "number"
    Transaction:
      description: "Contains information about a transaction"
      type: "object"
      x-examples:
        Ejemplo:
          status:
            status: "APPROVED"
            reason: "00"
            message: "approved"
            date: "2021-09-20T20:10:57-05:00"
          date: "2021-09-20T20:10:56-05:00"
          transactionDate: "2021-09-20T20:10:56-05:00"
          internalReference: 2
          reference: "1234567890"
          paymentMethod: "DF_VS"
          franchise: "visa"
          franchiseName: "Visa"
          issuerName: "Testing Bank"
          amount:
            currency: "USD"
            total: 1
          conversion:
            from:
              currency: "USD"
              total: 1
            to:
              currency: "USD"
              total: 1
            factor: 1
          authorization: "000000"
          receipt: "2"
          type: "AUTH_ONLY"
          refunded: "false"
          lastDigits: "0008"
          provider: "DATAFAST"
          discount:
          processorFields:
            id: "de7c331a0f5bebdd1996250296cdaf37"
            b24: "000"
          additional:
            merchantCode: "1000000505"
            terminalNumber: "PY100404"
            credit:
              code: "0"
              type: "00"
              groupCode: "C"
              installments: 0
            totalAmount: 1
            iceAmount: 0
            batch:
            line:
            bin: "411076"
            expiration: "1221"
      title: ""
      properties:
        status:
          $ref: "#/components/schemas/Status"
        date:
          type: "string"
          description: |
            EJ: `2021-09-20T21:51:59-05:00`
        transactionDate:
          type: "string"
          description: |
            EJ: `2021-09-20T21:51:59-05:00`
        internalReference:
          type: "number"
        reference:
          type: "string"
          minLength: 1
        paymentMethod:
          type: "string"
          minLength: 1
        franchise:
          type: "string"
          minLength: 1
        franchiseName:
          type: "string"
          minLength: 1
        issuerName:
          type: "string"
          minLength: 1
          nullable: true
        amount:
          $ref: "#/components/schemas/Amount"
        conversion:
          $ref: "#/components/schemas/AmountConversion"
        authorization:
          type: "string"
          minLength: 1
          nullable: true
        receipt:
          type: "string"
          maxLength: 16
          nullable: true
        type:
          type: "string"
          minLength: 1
        refunded:
          type: "boolean"
        lastDigits:
          type: "string"
          minLength: 1
          nullable: true
        provider:
          type: "string"
          enum:
            - "CREDIBANCO"
            - "REDEBAN"
            - "INTERDIN"
            - "DATAFAST"
            - "TUYA-DIRECT"
            - "BRASPAG"
            - "TRANSERVER"
            - "SABRE"
            - "EVERTEC"
            - "ACH"
            - "ATH-AVALNET"
            - "SUPERGIROS"
            - "TECNICARD"
            - "MEDIANET"
            - "AUSTRO"
            - "COMFANDI"
            - "PAYSTUDIO"
            - "FLAMINGO"
            - "ATH-MOVIL"
            - "EBUS"
            - "BANCOLOMBIA"
        discount:
          type: "object"
          nullable: true
          properties:
            code:
              type: string
            type:
              type: string
            amount:
              type: number
            base:
              type: number
            percentage:
              type: number
        processorFields:
          type: "object"
          properties:
            id:
              type: "string"
            b24:
              type: "string"
        additional:
          type: "object"
          description: |
            See more in [Additional data](/en/gateway/additional-data)
        preAuthorization:
          type: "object"
          items:
            type: "object"
            properties:
              condition:
                type: "string"
              internalReference:
                type: "number"
              authorization:
                type: "string"
                minLength: 1
                nullable: true
              receipt:
                type: "string"
                minLength: 1
                nullable: true
              amount:
                $ref: "#/components/schemas/Amount"
              salt:
                type: "string"
        dispersion:
          type: "array"
          items:
            type: "object"
            properties:
              status:
                $ref: "#/components/schemas/Status"
              agreement:
                type: "integer"
                nullable: true
              agreementType:
                type: "string"
                enum:
                  - "AIRLINE"
                  - "MERCHANT"
              authorization:
                type: "string"
                minLength: 1
                nullable: true
              receipt:
                type: "string"
                minLength: 1
                nullable: true
              amount:
                $ref: "#/components/schemas/Amount"
              refunded:
                type: "boolean"
              paymentMethod:
                type: "string"
      required:
        - "status"
        - "provider"
        - "internalReference"
        - "reference"
        - "paymentMethod"
        - "franchise"
        - "franchiseName"
        - "issuerName"
        - "amount"
        - "conversion"
        - "authorization"
        - "receipt"
        - "type"
        - "refunded"
        - "lastDigits"
        - "discount"
        - "processorFields"
        - "additional"
